runtime: python37 

instance_class: F2

env_variables:
  BUCKET_NAME: "example-gcs-bucket"

handlers:
- url: .html
  static_dir: static/.html

- url: .*
  secure: always
  redirect_http_response_code: 301
  script: auto

